#!/bin/bash
#SBATCH --time=00:05:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --job-name="genome indexing"
#SBATCH --account=def-dirwin
#SBATCH --output=job_%j.out
#SBATCH --mail-user=cwc@zoology.ubc.ca
#SBATCH --mail-type=ALL 

# Load Samtools and its dependencies
module load StdEnv/2023 samtools/1.18

# Select part of the genome with Samtools
srun \
samtools faidx \
/home/cwcharle/projects/def-dirwin/cwcharle/yeast/GCF_000146045.2_R64_genomic.fna \
NC_001141.2:1000-1200 \
--output /home/cwcharle/scratch/yeast/yeast_subset.fna

